import React from "react";
import type { Metadata } from "next";
import "../public/fonts/font.css"; // Import font.css
import "./globals.css";
import GotoTop from "./Ui/GotoTop";
import StateContextProvider from "./context/StateContext";

// Updated LayoutProps interface
export interface LayoutProps {
  children: React.ReactNode;
  types: React.ReactNode; // Add more properties as needed
}

export const metadata: Metadata = {
  title: "Lounge Luxe",
  description: "Generated by create next app",
};

export default function RootLayout({ children, types }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        {/* Font applied through CSS (refer to globals.css or the stylesheet) */}
        <StateContextProvider>
          {children}
          <GotoTop />
        </StateContextProvider>
      </body>
    </html>
  );
}
