import React from "react";
import type { Metadata } from "next";
import "../public/fonts/font.css";
import "./globals.css";
import GotoTop from "./Ui/GotoTop";
import StateContextProvider from "./context/StateContext";

export const metadata: Metadata = {
  title: " Lounge Luxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-montserrat-poppins font-non-latin">
        {" "}
        <StateContextProvider>
          {children}
          <GotoTop />
        </StateContextProvider>
      </body>
    </html>
  );
}
